#!/usr/bin/env python
'''
Autogenerated code using arya.py
Original Object Document Input: 
{"fvTenant":{"attributes":{"dn":"uni/tn-arya_tenant","name":"arya_tenant","rn":"tn-arya_tenant","status":"created"},"children":[{"fvCtx":{"attributes":{"dn":"uni/tn-arya_tenant/ctx-arya_vrf","name":"arya_vrf","rn":"ctx-arya_vrf","status":"created"},"children":[]}}]}}

raise RuntimeError('Please review the auto generated code before ' +
                    'executing the output. Some placeholders will ' +
                    'need to be changed')


Validated working BDR 20200911
  Note: I had to change line 443 in arya.py:
    https://github.com/datacenter/arya/issues/12
'''

# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.fv
import cobra.model.pol
from cobra.internal.codec.xmlcodec import toXMLStr

# Disable insecure certificate warning
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# log into an APIC and create a directory object
ls = cobra.mit.session.LoginSession('https://sandboxapicdc.cisco.com', 'admin', 'ciscopsdt')
md = cobra.mit.access.MoDirectory(ls)
md.login()

# the top level object on which operations will be made
topMo = cobra.model.pol.Uni('')


# build the request using cobra syntax
fvTenant = cobra.model.fv.Tenant(topMo, name='arya_tenant')
fvCtx = cobra.model.fv.Ctx(fvTenant, name='arya_vrf')


# commit the generated code to APIC
print(toXMLStr(topMo))
c = cobra.mit.request.ConfigRequest()
c.addMo(topMo)
md.commit(c)

